version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: footpilot
      POSTGRES_USER: footpilot
      POSTGRES_PASSWORD: footpilot_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U footpilot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://footpilot:footpilot_secret@db:5432/footpilot
      JWT_SECRET: fp_jwt_secret_change_in_production_use_256bit_random
      PORT: 3001
      NODE_ENV: production
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USER: footpilot.notifications@gmail.com
      SMTP_PASS: "qfbc otbq acyh jqjz"
      SMTP_FROM: "FootPilot <footpilot.notifications@gmail.com>"
      APP_URL: http://localhost:3000
      CORS_ORIGIN: http://localhost:3000
      STRIPE_SECRET_KEY: sk_test_51TTn9K2OZ7hHGPfzODX6oDwTCgrzY5NxFzzeuwRu9qrkKCZsWDybLpQRsLJtv7SMWqh7RNasPAHnnicrCMI7Tq0a00CRsNNYyc
      STRIPE_WEBHOOK_SECRET: whsec_ff17148cc0e061331e363a02bbecc4cccfbf354268446b113a907ab7b62af253
      STRIPE_SUBSCRIPTION_PRICE_ID: price_1TTnEj2OZ7hHGPfzV4KfGQ3U
      STRIPE_PAYMENT_PRICE_ID: price_1TTnF42OZ7hHGPfzVur95MSA
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
